name: Code-Linter

on: push

jobs:
  code-linter:
    name: Lint code base
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        with:
          node-version: '18.x'

      - name: install NPM Packages
        run: yarn install
     
      - name: Build Project
        run: yarn build
        
        