name: Code-Linter

on: 
 push:
   branches: [ main, dev ]
 pull_request:
   branches: [ main, dev ]
jobs:
 test:
   timeout-minutes: 60
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
       node-version: '18.x'
   - name: Install dependencies
     run: yarn install
   - name: Install Playwright Browsers
     run: yarn add @playwright/test
   - name: Run Playwright tests
     run: npx @playwright test
   - uses: actions/upload-artifact@v2
     if: always()
     with:
       name: playwright-report
       path: playwright-report/
       retention-days: 30
        
        